name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 初始化Gradle包装器
    - name: Setup Gradle
      run: |
        ./gradlew wrapper --gradle-version 8.2
        chmod +x gradlew
        ./gradlew --version

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 完整构建流程
    - name: Build APK
      run: ./gradlew assembleDebug

    # APK验证
    - name: Verify APK
      run: |
        echo "构建输出目录:"
        ls -lR app/build/outputs/apk
        echo "\nAPK文件:"
        find . -name "*.apk"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pixel-plane-game
        path: app/build/outputs/apk/**/*.apk