name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      run: |
        # 添加详细日志
        ./gradlew assembleDebug --stacktrace --info

    - name: Verify build outputs
      run: |
        echo "完整项目结构:"
        find . -type d | sort
        echo "\n构建输出目录:"
        ls -lR app/build/outputs || true

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: pixel-plane-game
        path: app/build/outputs/apk/**/*.apk
