name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 终极APK路径扫描
    - name: Locate APK files
      run: |
        echo "项目结构:"
        find . -type d | sort
        echo "\n所有APK文件:"
        find . -name "*.apk" || echo "未找到APK文件"
        echo "\n构建输出目录:"
        ls -lR build/ app/build/ || true

    # 上传整个构建目录
    - name: Upload all build outputs
      uses: actions/upload-artifact@v4
      with:
        name: full-build-artifacts
        path: |
          build/
          app/build/
        retention-days: 1